apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: cert-manager

helmCharts:
  - name: cert-manager
    repo: https://charts.jetstack.io
    version: v1.17.0
    releaseName: cert-manager
    valuesInline:
      crds:
        enabled: true
      prometheus:
        enabled: true
# resources:
#   - ns.yaml
