# File: overlays/dev/values.yaml
replicaCount: 1

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 100m
    memory: 128Mi

monitoring:
  podMonitorEnabled: false

config:
  data:
    WATCH_NAMESPACE: "dev-*"
