kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: k8s-mode
  namespace: arc-runners # just showing the test namespace
provisioner: file.csi.azure.com # change this to your provisioner
allowVolumeExpansion: true # probably not strictly necessary
reclaimPolicy: Delete
mountOptions:
  - dir_mode=0777 # this mounts at a directory needing this
  - file_mode=0777
  - uid=1001 # match your pod's user id, this is for actions/actions-runner
  - gid=1001
  - mfsymlinks
  - cache=strict
  - actimeo=30