#apiVersion: kustomize.config.k8s.io/v1beta1
#kind: Kustomization
#
#resources:
#  - base/controller
#  - base/runner-set
#  - base/argocd-cm.yaml

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

helmCharts:
  - name: gha-runner-scale-set-controller
    repo: oci://ghcr.io/actions/actions-runner-controller-charts
    version: 0.10.1
    releaseName: arc
    namespace: arc-systems
    includeCRDs: true

#  - name: gha-runner-scale-set
#    repo: oci://ghcr.io/actions/actions-runner-controller-charts
#    version: 0.10.1
#    releaseName: arc-runner-set
#    namespace: arc-runners
#    valuesInline:
#      githubConfigUrl: "https://github.com/<your_enterprise/org/repo>"
#      githubConfigSecret:
#        github_token: "<PAT>"

resources:
  - namespace-arc-systems.yaml
#  - namespace-arc-runners.yaml
