apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: k8s-mode
  namespace: arc-runners
provisioner: rancher.io/local-path
allowVolumeExpansion: true
reclaimPolicy: Delete
#volumeBindingMode: WaitForFirstConsumer
parameters:
  path: /var/local-path-provisioner
