# .github/workflows/k8s-deploy.yml
name: Deploy argocd to On-Prem Kubernetes

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: arc-runner-set

    steps:
    # Step 1: Check out the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 4: Set up kubectl with kubeconfig for on-prem cluster
    - name: Set up kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'latest'

    - name: Configure kubeconfig
      run: echo "${{ secrets.KUBECONFIG }}" | base64 --decode > kubeconfig && export KUBECONFIG=kubeconfig

    # Step 5: Deploy to Kubernetes
    - name: Deploy to Kubernetes
      run: |
        kubectl get pods -n default
